### ISSUE TITLE
I really want a clear document

### ISSUE THREAD

**Issue by qq332769043** [bizzehdee/System.Net.Torrent#8] opened 2018-04-25 19:49 UTC
em......

**Comment by chez14** [comment] 2018-06-01 23:07
Felt like... duplicate of #7...?

**Comment by bizzehdee** [comment] 2018-06-03 21:19
"Want"? this is a free dump of code i worked on for something i needed for myself. If you want to use it, figure out how it worked, if you dont want to use it, go figure out one of the far more complicated libraries...

**Closed** 2018-06-03 21:19 UTC
